apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: login-nodejs
  namespace: beast-idp-demo
spec:
  template:
    spec:
      containers:
      - image: docker.io/rabay108/login-nodejs
        env:
        - name: TARGET
          value: "Login test push Node.js v1"
