apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: login-nodejs
  namespace: beast-idp-demo
spec:
  template:
    metadata:
      annotations:
        # the minimum number of pods to scale down to
        autoscaling.knative.dev/minScale: "1"
    spec:	
      containers:
      - image: docker.io/rabay108/login-nodejs
        env:
        - name: TARGET
          value: "Login Get passing fields Test Node.js "
